// Code generated by "stringer -type=ImpactStatus"; DO NOT EDIT.

package caseconst

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoImpact-0]
	_ = x[WithImpact-1]
	_ = x[NotApplicable-2]
}

const _ImpactStatus_name = "NoImpactWithImpactNotApplicable"

var _ImpactStatus_index = [...]uint8{0, 8, 18, 31}

func (i ImpactStatus) String() string {
	if i < 0 || i >= ImpactStatus(len(_ImpactStatus_index)-1) {
		return "ImpactStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ImpactStatus_name[_ImpactStatus_index[i]:_ImpactStatus_index[i+1]]
}
