
//resolutionstatus_enummethods.go is auto generated by utility enummethods. DO NOT EDIT
//This file have some type methods implementing the Enumerator and json.Marshaler, json.Unmarshaler interfaces.
package caseconst

import (
	
	"strings"
	"github.com/ivi81/enummethods/enumerator"
)


//MarshalJSON - реализует метод интерфейса json.Marshaler
func (m ResolutionStatus) MarshalJSON() ([]byte, error) {
	return enumerator.MarshalJSON(m)
}

//UnmarshalJSON - реализует метод интерфейса json.UnMarshaler
func (m *ResolutionStatus) UnmarshalJSON(data []byte) error {
	return enumerator.UnmarshalJSON(m, data)
}


//IsValid проверка корректности значения
//Реализует интерфейс Validator
func (m ResolutionStatus) IsValid() bool {

	switch m {
	case
		Indeterminate,
		FalsePositive,
		TruePositive,
		Other,
		Duplicated:
		return true
	}
	return false
}


//SetValue конвертация строки в значение типа
//Реализует интерфейс Unstringer
func (m *ResolutionStatus) SetValue(s string) bool {
	i := strings.Index(_ResolutionStatus_name, s)
	if i != -1 {

		for index, v := range _ResolutionStatus_index {
			if i-int(v) == 0 {
				*m = ResolutionStatus(index)
				return true
			}
		}
	}
	return false
}

