// Code generated by "stringer -type=FilterConst"; DO NOT EDIT.

package v1const

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[_lt-0]
	_ = x[_lte-1]
	_ = x[_gt-2]
	_ = x[_gte-3]
	_ = x[_ne-4]
	_ = x[_not-5]
	_ = x[_and-6]
	_ = x[_or-7]
	_ = x[_between-8]
	_ = x[_like-9]
	_ = x[_contains-10]
	_ = x[_field-11]
	_ = x[_value-12]
	_ = x[_from-13]
	_ = x[_to-14]
}

const _FilterConst_name = "_lt_lte_gt_gte_ne_not_and_or_between_like_contains_field_value_from_to"

var _FilterConst_index = [...]uint8{0, 3, 7, 10, 14, 17, 21, 25, 28, 36, 41, 50, 56, 62, 67, 70}

func (i FilterConst) String() string {
	if i < 0 || i >= FilterConst(len(_FilterConst_index)-1) {
		return "FilterConst(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FilterConst_name[_FilterConst_index[i]:_FilterConst_index[i+1]]
}
