// Code generated by "stringer -type=PageConst"; DO NOT EDIT.

package v1const

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[from-0]
	_ = x[to-1]
	_ = x[extraData-2]
}

const _PageConst_name = "fromtoextraData"

var _PageConst_index = [...]uint8{0, 4, 6, 15}

func (i PageConst) String() string {
	if i < 0 || i >= PageConst(len(_PageConst_index)-1) {
		return "PageConst(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PageConst_name[_PageConst_index[i]:_PageConst_index[i+1]]
}
