// Code generated by "stringer -type=SubQueryConst"; DO NOT EDIT.

package v1const

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[count-1]
	_ = x[page-2]
	_ = x[observables-3]
	_ = x[assignableUsers-4]
	_ = x[filter-5]
	_ = x[linkedCases-6]
	_ = x[tasks-7]
	_ = x[logs-8]
	_ = x[aggregation-9]
	_ = x[actions-10]
	_ = x[organisations-11]
	_ = x[output-12]
	_ = x[sort-13]
	_ = x[alerts-14]
	_ = x[limitedCount-15]
}

const _SubQueryConst_name = "countpageobservablesassignableUsersfilterlinkedCasestaskslogsaggregationactionsorganisationsoutputsortalertslimitedCount"

var _SubQueryConst_index = [...]uint8{0, 5, 9, 20, 35, 41, 52, 57, 61, 72, 79, 92, 98, 102, 108, 120}

func (i SubQueryConst) String() string {
	i -= 1
	if i < 0 || i >= SubQueryConst(len(_SubQueryConst_index)-1) {
		return "SubQueryConst(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _SubQueryConst_name[_SubQueryConst_index[i]:_SubQueryConst_index[i+1]]
}
