
//hiveobjecttype_enummethods.go is auto generated by utility enummethods. DO NOT EDIT
//This file have some type methods implementing the Enumerator and json.Marshaler, json.Unmarshaler interfaces.
package common

import (
	
	"github.com/ivi81/enummethods/enumerator"
)


//MarshalJSON - реализует метод интерфейса json.Marshaler
func (m HiveObjectType) MarshalJSON() ([]byte, error) {
	return enumerator.MarshalJSON(m)
}

//UnmarshalJSON - реализует метод интерфейса json.UnMarshaler
func (m *HiveObjectType) UnmarshalJSON(data []byte) error {
	return enumerator.UnmarshalJSON(m, data)
}


//IsValid проверка корректности значения
//Реализует интерфейс Validator
func (m HiveObjectType) IsValid() bool {

	switch m {
	case
		HIVECASE,
		HIVECASEAPI1,
		HIVEARTIFACT,
		HIVEARTIFACTAPI1,
		HIVETASK,
		HIVETASKAPI1,
		HIVETASKLOG,
		HIVETASKLOGAPI1,
		HIVEALERT,
		HIVEALERTAPI1,
		HIVEORG,
		HIVEORGAPI1:
		return true
	}
	return false
}


//String конвертация значения типа в строку. 
//Реализует интерфейс Stringer
func (m HiveObjectType) String() string {
	if m.IsValid() {
		return hiveObjectType[m]
	}
	return ""
}


//SetValue - конвертация строки в значение перечислимого типа.
//Реализует интерфейс Unstringer
func (m *HiveObjectType) SetValue(s string) bool {
	for i, v := range hiveObjectType {
		if v == s {
			*m = HiveObjectType(i)
			return true
		}
	}
	return false
}
