
//status_enummethods.go is auto generated by utility enummethods. DO NOT EDIT
//This file have some type methods implementing the Enumerator and json.Marshaler, json.Unmarshaler interfaces.
package taskconst

import (
	
	"strings"
	"github.com/ivi81/enummethods/enumerator"
)


//MarshalJSON - реализует метод интерфейса json.Marshaler
func (m Status) MarshalJSON() ([]byte, error) {
	return enumerator.MarshalJSON(m)
}

//UnmarshalJSON - реализует метод интерфейса json.UnMarshaler
func (m *Status) UnmarshalJSON(data []byte) error {
	return enumerator.UnmarshalJSON(m, data)
}


//IsValid проверка корректности значения
//Реализует интерфейс Validator
func (m Status) IsValid() bool {

	switch m {
	case
		Waiting,
		InProgress,
		Completed,
		Cancel:
		return true
	}
	return false
}


//SetValue конвертация строки в значение типа
//Реализует интерфейс Unstringer
func (m *Status) SetValue(s string) bool {
	i := strings.Index(_Status_name, s)
	if i != -1 {

		for index, v := range _Status_index {
			if i-int(v) == 0 {
				*m = Status(index)
				return true
			}
		}
	}
	return false
}

