package export

import (
	"time"

	"gitlab.cloud.gcm/i.ippolitov/go-thehiveclient/api/cons/alertconst"
)

//Optional attributes:
//- caseTemplate (string) : case template to use when a case is created from this alert.
//If the alert specifies a non-existent case template or doesn't supply one,
//TheHive will import the alert into a case using a case template that has the exact same name as the alert's type if it exists.
//For example, if you raise an alert with a type value of splunk and you do not provide the caseTemplate attribute or supply a non-existent one (for example splink),
//TheHive will import the alert using the case template called splunk if it exists.
//Otherwise, the alert will be imported using an empty case (i.e. from scratch).

//Attributes generated by the backend:
//- lastSyncDate (date) : date of the last synchronization
//- case (string) : id of the case, if created

//Alert ID is computed from type, source andsourceRef.

/*{
	"_id": "~43618512",
	"id": "~43618512",
	"createdBy": "[email protected]",
	"updatedBy": null,
	"createdAt": 1618344277475,
	"updatedAt": null,
	"_type": "alert",
	"type": "testing",
	"source": "create-alert.py",
	"sourceRef": "85a766ec",
	"externalLink": null,
	"case": "~122884120",
	"title": "Alert 85a766ec-060a-49a0-bc82-c672b6e51e6c",
	"description": "N/A",
	"severity": 1,
	"date": 1618344277000,
	"tags": [
	  "sample"
	],
	"tlp": 3,
	"pap": 2,
	"status": "Imported",
	"follow": true,
	"customFields": {
	  "company": {
		"string": "Customer 1"
	  }
	},
	"caseTemplate": null,
	"artifacts": [],
	"similarCases": []
  }*/

//HiveAlertReqAttr описывает атрибуты обязательные для Alert:
//- Title : заголовок Case
//- Description : описание Case
//- Severity (number) : строгость Case (1: low; 2: medium; 3: high) default=2
//- Date (date) : Дата и время сработки Alert-а, поумолчанию берется текущее время "now"
//- Flag (boolean) : flag of the case default=false
//- Tlp (number) : значение по протоколу TLP (0: white; 1: green; 2: amber; 3: red), по умолчанию "2"
//- Status (AlertStatus) : статус Alert-а (New, Updated, Ignored, Imported) default=New
//- Type (string) : тип Alert-а (только для чтения)
//- Source (string) : источник Alert-а (read only)
//- SourceRef (string) : source reference of the alert (read only)
//- Artifacts (multi-artifact) : artifact of the alert. It is a array of JSON object containing artifact attributes default=empty
//- Follow (boolean) : if true, the alert becomes active when updated default=true
type HiveAlertReqAttr struct {
	Title       string            `json:"title,omitempty"`
	Description string            `json:"description,omitempty"`
	Severity    int               `json:"severity,omitempty"`
	Date        time.Time         `json:"date"`
	Tags        []string          `json:"tags"`
	Tlp         int               `json:"tlp"`
	Status      alertconst.Status `json:"status"`
	Type        string            `json:"type,omitempty"`
	Source      string            `json:"source,omitempty"`
	SourceRef   string            `json:"sourceRef,omitempty"`
	Artifacts   []interface{}     `json:"artifacts,omitempty"`
	Follow      bool              `json:"follow",omitempty`
}

//HiveAlertOptionAttr описывает атрибуты не обязательные для Case:
//- ResolutionStatus (caseResolutionStatus) : решение по Case (Indeterminate, FalsePositive, TruePositive, Other or Duplicated)
//- ImpactStatus (caseImpactStatus) : impact status of the case (NoImpact, WithImpact or NotApplicable)
//- Summary : краткое описание case, заполняется при закрытии Case-а
//- EndDate : дата принятия решения
type HiveAlertOptionAttr struct {
}

//HiveAlertBackendAttr описывает атрибуты формируемые Hive-ом и возвращаемые при запросах к нему
//- Status (caseStatus) : состояние Case (Open, Resolved or Deleted), по умолчанию "Open"
//- CaseId (number) : идентификатор Сase (генерируется атоматически )
//- MergeInto (string) : идентификатор Сase созданого в реультате слияния других Case-ов
//- MergeFrom (multi-string) : идентификаторы Case-ов участвовавших в слияние
type HiveAlertBackendAttr struct {
}

type HiveAlert struct {
}
